### ISSUE TITLE
sc-mb-import: Import Button fails when artist not found in MB

### ISSUE THREAD

**Issue by zabe40** [garylaski/userscripts#15]
I ran into some trouble trying to import this release: https://soundcloud.com/smoothietunes/sets/blend-press-play-compilation. After pressing the button nothing happened except I got an error in the console, but it just said `undefined`. Sometimes I would also get a musicbrainz rate limit for my troubles. After a little poking around it seems like the error occurs when `addArtistMBID` is called, which I proved to myself by commenting out everywhere its called and then it worked perfectly (except for not filling out the artist's MBID).

**Comment by garylaski** [comment]
I've done a rewrite. It looks to me like this is working now, since I disable the button until the user scrolls down to load tracks that otherwise might not be visible (Just the way sc works). Let me know if the update solved the issue.

**Comment by zabe40** [comment]
Yeah, it works great now, thanks so much!
