### ISSUE TITLE
Import button no longer works

### ISSUE THREAD

**Issue by UltimateRiff** [garylaski/userscripts#6]
it seems after several updates on Feb. 19, the import button no longer works. I click it, and nothing happens.

I'm on Windows 11 with Chrome and Tampermonkey, both up-to-date to my knowledge (if you need version numbers, I can hunt them down)
continuing testing with [this release](https://soundcloud.com/underg-d/shes-not-there).

**Comment by garylaski** [comment]
Looks like a helper function was not added to the commit. Should work now.
